name: Test TR-1909 Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test runner
        run: |
          echo "GitHub Runner is working"
          whoami
          hostname

      - name: Test Kubernetes
        run: |
          kubectl get nodes
          kubectl get pods -n tr1909

      - name: Test Helm
        run: |
          helm version
